<h1>Index = Retrieve</h1>
<table class="table">
<tr>
	<th>id</th>
	<th>title</th>
	<th>artist</th>
</tr>
<?php
	foreach ($this->paginator as $row) {
?>
		<tr>
			<td><?php  echo $row->id; // The row is an ArrayObject $row->usr_id and $row['usr_id'] with both work?></td>
			<td><?php  echo $row['title']; ?></td>
			<td><?php  echo $row['artist']; ?></td>
		</tr>
<?php
	}
?>
</table>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding', // All, Elastic, Jumping, Sliding
                                    'search_pagination.phtml', array('route' => 'paginator')); ?>
<!-- 'search_pagination.phtml' 'item_pagination.phtml' dropdown_pagination.phtml -->